## basys3_soc_cam.xdc — Combined Constraints for RISC-V SoC + OV7670 Camera
## Target: basys3_soc_cam_top.v

## Clock (100 MHz)
set_property PACKAGE_PIN W5 [get_ports clk100]
set_property IOSTANDARD LVCMOS33 [get_ports clk100]
create_clock -period 10.000 -name sys_clk_pin -waveform {0.000 5.000} [get_ports clk100]

## Reset & Buttons
set_property PACKAGE_PIN U18 [get_ports btn_rst]
set_property IOSTANDARD LVCMOS33 [get_ports btn_rst]
set_property PACKAGE_PIN T18 [get_ports btn_u]
set_property IOSTANDARD LVCMOS33 [get_ports btn_u]
set_property PACKAGE_PIN W19 [get_ports btn_l]
set_property IOSTANDARD LVCMOS33 [get_ports btn_l]
set_property PACKAGE_PIN T17 [get_ports btn_r]
set_property IOSTANDARD LVCMOS33 [get_ports btn_r]
set_property PACKAGE_PIN U17 [get_ports btn_d]
set_property IOSTANDARD LVCMOS33 [get_ports btn_d]

## Switches
set_property PACKAGE_PIN V17 [get_ports {sw[0]}]
set_property PACKAGE_PIN V16 [get_ports {sw[1]}]
set_property PACKAGE_PIN W16 [get_ports {sw[2]}]
set_property PACKAGE_PIN W17 [get_ports {sw[3]}]
set_property PACKAGE_PIN W15 [get_ports {sw[4]}]
set_property PACKAGE_PIN V15 [get_ports {sw[5]}]
set_property PACKAGE_PIN W14 [get_ports {sw[6]}]
set_property PACKAGE_PIN W13 [get_ports {sw[7]}]
set_property PACKAGE_PIN V2  [get_ports {sw[8]}]
set_property PACKAGE_PIN T3  [get_ports {sw[9]}]
set_property PACKAGE_PIN T2  [get_ports {sw[10]}]
set_property PACKAGE_PIN R3  [get_ports {sw[11]}]
set_property PACKAGE_PIN W2  [get_ports {sw[12]}]
set_property PACKAGE_PIN U1  [get_ports {sw[13]}]
set_property PACKAGE_PIN T1  [get_ports {sw[14]}]
set_property PACKAGE_PIN R2  [get_ports {sw[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[*]}]

## LEDs
set_property PACKAGE_PIN U16 [get_ports {led[0]}]
set_property PACKAGE_PIN E19 [get_ports {led[1]}]
set_property PACKAGE_PIN U19 [get_ports {led[2]}]
set_property PACKAGE_PIN V19 [get_ports {led[3]}]
set_property PACKAGE_PIN W18 [get_ports {led[4]}]
set_property PACKAGE_PIN U15 [get_ports {led[5]}]
set_property PACKAGE_PIN U14 [get_ports {led[6]}]
set_property PACKAGE_PIN V14 [get_ports {led[7]}]
set_property PACKAGE_PIN V13 [get_ports {led[8]}]
set_property PACKAGE_PIN V3  [get_ports {led[9]}]
set_property PACKAGE_PIN W3  [get_ports {led[10]}]
set_property PACKAGE_PIN U3  [get_ports {led[11]}]
set_property PACKAGE_PIN P3  [get_ports {led[12]}]
set_property PACKAGE_PIN N3  [get_ports {led[13]}]
set_property PACKAGE_PIN P1  [get_ports {led[14]}]
set_property PACKAGE_PIN L1  [get_ports {led[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[*]}]

## UART (USB-Serial)
set_property PACKAGE_PIN A18 [get_ports uart_txd_out]
set_property PACKAGE_PIN B18 [get_ports uart_rxd_in]
set_property IOSTANDARD LVCMOS33 [get_ports uart_txd_out]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rxd_in]

## VGA
set_property PACKAGE_PIN G19 [get_ports {vga_r[0]}]
set_property PACKAGE_PIN H19 [get_ports {vga_r[1]}]
set_property PACKAGE_PIN J19 [get_ports {vga_r[2]}]
set_property PACKAGE_PIN N19 [get_ports {vga_r[3]}]
set_property PACKAGE_PIN J17 [get_ports {vga_g[0]}]
set_property PACKAGE_PIN H17 [get_ports {vga_g[1]}]
set_property PACKAGE_PIN G17 [get_ports {vga_g[2]}]
set_property PACKAGE_PIN D17 [get_ports {vga_g[3]}]
set_property PACKAGE_PIN N18 [get_ports {vga_b[0]}]
set_property PACKAGE_PIN L18 [get_ports {vga_b[1]}]
set_property PACKAGE_PIN K18 [get_ports {vga_b[2]}]
set_property PACKAGE_PIN J18 [get_ports {vga_b[3]}]
set_property PACKAGE_PIN P19 [get_ports vga_hsync]
set_property PACKAGE_PIN R19 [get_ports vga_vsync]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports vga_hsync]
set_property IOSTANDARD LVCMOS33 [get_ports vga_vsync]

## OV7670 Camera pins
set_property PACKAGE_PIN A14 [get_ports ov7670_pwdn]
set_property PACKAGE_PIN A15 [get_ports ov7670_reset]
set_property PACKAGE_PIN M18 [get_ports ov7670_xclk]
set_property PACKAGE_PIN M19 [get_ports ov7670_pclk]
set_property PACKAGE_PIN P17 [get_ports ov7670_vsync]
set_property PACKAGE_PIN N17 [get_ports ov7670_href]
set_property IOSTANDARD LVCMOS33 [get_ports ov7670_pwdn]
set_property IOSTANDARD LVCMOS33 [get_ports ov7670_reset]
set_property IOSTANDARD LVCMOS33 [get_ports ov7670_xclk]
set_property IOSTANDARD LVCMOS33 [get_ports ov7670_pclk]
set_property IOSTANDARD LVCMOS33 [get_ports ov7670_vsync]
set_property IOSTANDARD LVCMOS33 [get_ports ov7670_href]
create_clock -period 40.000 -name cam_pclk [get_ports ov7670_pclk]
set_clock_groups -asynchronous -group [get_clocks sys_clk_pin] -group [get_clocks cam_pclk]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets -of_objects [get_ports ov7670_pclk]]

set_property PACKAGE_PIN R18 [get_ports ov7670_sioc]
set_property PACKAGE_PIN P18 [get_ports ov7670_siod]
set_property IOSTANDARD LVCMOS33 [get_ports ov7670_sioc]
set_property IOSTANDARD LVCMOS33 [get_ports ov7670_siod]
set_property PULLUP TRUE [get_ports ov7670_siod]
set_property PULLUP TRUE [get_ports ov7670_sioc]

set_property PACKAGE_PIN A16 [get_ports {ov7670_data[0]}]
set_property PACKAGE_PIN A17 [get_ports {ov7670_data[1]}]
set_property PACKAGE_PIN B15 [get_ports {ov7670_data[2]}]
set_property PACKAGE_PIN C15 [get_ports {ov7670_data[3]}]
set_property PACKAGE_PIN B16 [get_ports {ov7670_data[4]}]
set_property PACKAGE_PIN C16 [get_ports {ov7670_data[5]}]
set_property PACKAGE_PIN K17 [get_ports {ov7670_data[6]}]
set_property PACKAGE_PIN L17 [get_ports {ov7670_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ov7670_data[*]}]

## Configuration
set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
